#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it
# DB referring to Database
DB_USER="root"
DB_PASSWORD="$1"
DB_NAME="backup.sql"
BACKUP_PATH="."
DATE=$(date +%d-%m-%Y)

# create a MySQL dump of all databases
mysqldump -u$DB_USER -p"$DB_PASSWORD" --all-databases > $BACKUP_PATH/$DB_NAME

# Compress the dump file to a tar.gz archive
tar -czvf $BACKUP_PATH/"$DATE".tar.gz -C $BACKUP_PATH $DB_NAME
