#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
sudo apt update
sudo apt install nginx -y
sudo bash -c "echo 'Hello World' > /var/www/html/index.html"
sudo service nginx start
sudo service nginx stop
sudo service nginx start
