#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt update
sudo apt install nginx -y
echo -e "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOT

#Configure Nginx to use the custom 404 page
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /etc/nginx/html;
        index index.html index.htm;
        error_page 404 /404.html;
    }

    location = /404.html {
        root /etc/nginx/html;
        internal;
    }


}
EOT

sudo service nginx restart
