#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt update
sudo apt install nginx -y
touch /etc/nginx/html/index.html
echo "Hello World!" >  /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

#Configure Nginx to use the custom 404 page
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /etc/nginx/html;

    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;

    location = /404.html {
        root /etc/nginx/html;
        internal;
    }


}" > /etc/nginx/sites-available/default

sudo service nginx restart
