#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02), The name of the custom HTTP header must be X-Served-By, The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt update
sudo apt install -y nginx

echo 'Hello World!' > /etc/nginx/html/index.html
echo 'Ceci n'\''est pas une page' > /etc/nginx/html/404.html
printf "%s" 'server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html;

    location / {
    add_header X-Served-By $hostname;
    }
    location /redirect_me {
         return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }

}' > /etc/nginx/sites-available/default

sudo service nginx restart
