#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt update
sudo apt install -y nginx

sudo echo 'Hello World!' > /var/www/html/index.html
sudo echo 'Ceci n'\''est pas une page' > /var/www/html/404.html

echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
    add_header X-Served-By $hostname;
    }

    location /redirect_me {
         return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
        internal;
    }

}' > /etc/nginx/sites-available/default

sudo service nginx restart
