#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt update -y
sudo apt install software-properties-common -y
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt update -y
sudo apt install haproxy -y
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo \
        "
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 259096-web-01 34.202.164.69
    server 259096-web-02 100.25.41.114" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
