#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it
DB_PASSWORD="$1"
DATE=$(date +%d-%m-%Y)

# create a MySQL dump of all databases
mysqldump -uroot -p"$DB_PASSWORD" --all-databases > backup.sql

# Compress the dump file to a tar.gz archive
 vzft"$DATE" -C $BACKUP_PATH $DB_NAME
