#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it

# create a MySQL dump of all databases
mysqldump -uroot -p"$1" --all-databases > backup.sql

# Compress the dump file to a tar.gz archive
tar -czvf "$(date +%d-%m-%Y)".tar.gz backup.sql
