#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it
DB_PASSWORD="$1"
DB_NAME="backup.sql"
DATE=$(date +%d-%m-%Y)

# create a MySQL dump of all databases
mysqldump -uroot -p"$DB_PASSWORD" --all-databases > $DB_NAME

# Compress the dump file to a tar.gz archive
tar -czvf "$DATE".tar.gz $DB_NAME
