#!/usr/bin/env bash
# Write a Bash script with the minimum number of commands to automate your fix.
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
# Write a Bash script that configures a server to the above requirement
sudo service nginx start
NGINX_CONFIG="/etc/nginx/sites-enabled/default"

# substitute all occurences of listen 8080 default_server to listen 80 default_server
sudo sed -i 's/listen 8080 default_server/listen 80 default_server/g' $NGINX_CONFIG
sudo sed -i 's/listen \[::\]:8080 default_server ipv6only=on/listen [::]:80 default_server ipv6only=on/g' $NGINX_CONFIG
sudo service nginx reload
sudo service nginx start
