#!/usr/bin/env bash
# Write a Bash script with the minimum number of commands to automate your fix.
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
# Write a Bash script that configures a server to the above requirement
NGINX_CONFIG="/etc/nginx/sites-enabled/default"
rm $NGINX_CONFIG
ln -s /etc/nginx/sites-available/default $NGINX_CONFIG
sudo service nginx restart
