#!/usr/bin/env bash
# Write a Bash script with the minimum number of commands to automate your fix.
sudo sed -i 's/listen 8080 default_server/listen 80 default_server/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080 default_server ipv6only=on/listen [::]:80 default_server ipv6only=on/g' /etc/nginx/sites-enabled/default
sudo service nginx stop
