#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.
#+ Your script should only display:
#+ username
#+ user id
#+ Home directory path for the user

filename="/etc/passwd"
while read -r VAR_READ_FilE
do
	echo "${VAR_READ_FilE}"
	cut -d ":" -f 1,3,6 $filename
done < "$filename"
