#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd,
#+ using the while loop + IFS


filename="/etc/passwd"
while IFS=":" read -r username _ groupid _ homedirectory _ shell _ password _ gecos _ f3 _
do
	#echo "${VAR_READ_FilE}"

	echo "The user $username is part of the $groupid gang, lives in $homedirectory and rides $shell. $f3's place is protected by the passcode $password, more info about the user here: $gecos"
done < "$filename"
