#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and displays this data
#+ Requirements:
#+ The exact format must be:
#+ OCCURENCE_NUMBER IP HTTP_CODE
#+ In list format
#+ Ordered from the greatest to the lowest number of occurrences
#+ See example
#+ You must use awk
#+ You are not allowed to use while, for, until and cut

awk '{ count[$1, $9]++ } END {for (key in count) printf "    %4d %-15s\n", count[key], key}' OFS=" " ./apache-access.log | sort -rn
