#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
#+ display hours from 0 to 12
#+ display minutes from 1 to 59

hour=0

while ((hour <= 12))
do
    printf "Hour: %d\n" $hour
    minute=1

    while ((minute <= 59))
	do
	printf "%d\n" $minute
	((minute++))
	done

	((hour++))
done

