#!/usr/bin/env bash
#  Bash script that displays: The content of the current directory
#+ In a list format
#+ Where only the part of the name after the first dash is displayed

pwd="."

for i in "$pwd"/*
do
	filename=$(basename "$i")
	remove_dash="${filename#*-}"
	echo "${remove_dash#* }"
done
