#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements. localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/localhost/localhost\n127.0.0.2/' ~/hosts.new
sed -i 's/facebook.com/facebook.com\n8.8.8.8/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
