#!/usr/bin/env bash
# Bash script that configures the container so that Nginx is running as the nginx user
service nginx stop
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
service nginx start
