#!/usr/bin/env bash
# Bash script that configures the container so that Nginx is running as the nginx user

service nginx start
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
service nginx restart
